# Custom Language File for Launcher Customizer

[ejs.app]
title = "깅씨네 귀농일지2"

[ejs.landing]
mediaGitHubURL = "https://brave-gouda-839.notion.site/11865ab291e780adb5b8cf88e64cbeb9?pvs=4"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""

[ejs.settings]
sourceGithubLink = "https://github.com/Rascal7/gingsfarm"
supportLink = "https://github.com/Rascal7/gingsfarm/issues"

[ejs.welcome]
welcomeHeader = "깅씨네 귀농일지2에 오신 것을 환영합니다!"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
